backend:
  #name: test-repo
  name: git-gateway
  #repo: https://github.com/omerknysys/dcwebtech
  branch:  master

media_folder: "public/assets/img"
public_folder: "/assets/img"

collections:
  - name: Banner
    label: Banner Image button Text and Link
    files:
      - file: public/logo.json
        name: Banner Image button Text and Link
        label: 'Banner Image button Text and Link'
        fields:
          - name: "buttonText"
            label: "Button Text"
            widget: "string"
            required: false
          - name: "buttonLink"
            label: "Banner Image button Text and Link"
            widget: "select"
            options:
              - { label: "Why-US", value: "/whyus" }
              - { label: "Contact", value: "/contact" }
              - { label: "Services", value: "/services" }
            required: false
  - name: contact
    label: Contact Number
    files:
      - file: public/logo.json
        name: contact
        label: 'Contact Settings'
        fields:
          - name: "contact"
            label: "Contact Number"
            widget: "string"
  - name: email
    label: Email
    files:
      - file: public/logo.json
        name: email
        label: 'Email'
        fields:
          - name: "email"
            label: "Email"
            widget: "string"

  - name: title and subtitle
    label: Title and Subtitle
    files:
      - file: public/logo.json
        name: title and subtitle
        label: 'Title and Subtitle'
        fields:
          - name: "bannerTitle"
            label: "Banner Title"
            widget: "string"
          - name : "bannerSubtitle"
            label : "Banner Subtitle"
            widget : "string"
  - name: logo_Url
    label: Logo
    files:
        - file: public/logo.json
          name: logo_Url
          label: "Logo Settings"
          folder: "public/assets/img"
          fields:
            - name: "logo_Url"
              label: "Logo URL"
              widget: "image"
              choose_url: false
  
  - name: Banner Image
    label: Banner Image
    files:
        - file: public/logo.json
          name: Banner Image
          label: "Banner Images"
          folder: "public/assets/img"
          fields:
            - name: "bannerImg"
              label: "Banner Image"
              widget: "image"
              choose_url: false
              required : false
            - name: "bannerImgabout"
              label: "Banner Image About page"
              widget: "image"
              choose_url: false
              required: false


  - name: settings
    label: Settings
    files:
      - file: public/manifest.json
        name: manifest
        label: 'Manifest Settings'
        fields:
          - name: short_name
            label: 'Short Name'
            widget: string
            required: true
          - name: name
            label: 'Name'
            widget: string
            required: true
          - name: start_url
            label: 'Start URL'
            widget: string
            default: '.'
            required: true
          - name: display
            label: 'Display Type'
            widget: string
            default: 'standalone'
            required: true
          - name: theme_color
            label: 'Theme Color'
            widget: string
            default: '#000000'
            required: true
          - name: background_color
            label: 'Theme Color'
            widget: string
            default: '#FFFFFF'
            required: true
          - name: icons
            widget: list
            label: 'Icons'
            allow_add: true
            fields:
              - widget: string
                name: src
                label: Source
              - widget: string
                name: sizes
                label: 'Sizes'
              - widget: string
                name: type
                label: 'Mime Type'

