backend:
  name: git-gateway
  #repo: https://github.com/omerknysys/dcwebtech
  branch:  master

# media_folder: "public/images"
# public_folder: "images"
media_folder: static/assets
public_folder: /assets

collections:
  - name: contact
    label: Contact Number 
    files:
      - file: public/logo.json
        name: contact
        label: 'Contact Settings'
        fields:
          - name: "contact"
            label: "Contact Number"
            widget: "string"   
  - name: email
    label: Email 
    files:
      - file: public/logo.json
        name: email
        label: 'Email'
        fields:
          - name: "email"
            label: "Email"
            widget: "string"
  - name: logo_Url
    label: Logo
    files:
        - file: public/logo.json
          name: logo_Url
          label: "Logo Settings"
          folder: "static/assets"
          fields:
            - name: "logo_Url"
              label: "Logo URL"
              widget: "image"
              choose_url: false

  - name: Another blog
    label: Another Blog
    folder: Another blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }  

  - name: settings
    label: Settings
    files:
      - file: public/manifest.json
        name: manifest
        label: 'Manifest Settings'
        fields:
          - name: short_name
            label: 'Short Name'
            widget: string
            required: true
          - name: name
            label: 'Name'
            widget: string
            required: true
          - name: start_url
            label: 'Start URL'
            widget: string
            default: '.'
            required: true
          - name: display
            label: 'Display Type'
            widget: string
            default: 'standalone'
            required: true
          - name: theme_color
            label: 'Theme Color'
            widget: string
            default: '#000000'
            required: true
          - name: background_color
            label: 'Theme Color'
            widget: string
            default: '#FFFFFF'
            required: true
          - name: icons
            widget: list
            label: 'Icons'
            allow_add: true
            fields:
              - widget: string
                name: src
                label: Source
              - widget: string
                name: sizes
                label: 'Sizes'
              - widget: string
                name: type
                label: 'Mime Type'

  