backend:
  name: test-repo
  repo: https://github.com/omerknysys/dcwebtech
  branch:  master

# media_folder: "public/images"
# public_folder: "images"
media_folder: static/assets
public_folder: /assets

# collections:
#   - name: blog
#     label: Blog
#     folder: blog
#     create: true
#     fields:
#       - { name: path, label: Path }
#       - { name: date, label: Date, widget: datetime }
#       - { name: title, label: Title }
#       - { name: Sub-title, label: Sub Title }
#       - { name: body, label: Body, widget: markdown }
  
#   - name: Another blog
#     label: Another Blog
#     folder: Another blog
#     create: true
#     fields:
#       - { name: path, label: Path }
#       - { name: date, label: Date, widget: datetime }
#       - { name: title, label: Title }
#       - { name: body, label: Body, widget: markdown }

#   - name: settings
#     label: Settings
#     files:
#       - file: public/manifest.json
#         name: manifest
#         label: 'Manifest Settings'
#         fields:
#           - name: short_name
#             label: 'Short Name'
#             widget: string
#             required: true
#           - name: name
#             label: 'Name'
#             widget: string
#             required: true
#           - name: start_url
#             label: 'Start URL'
#             widget: string
#             default: '.'
#             required: true
#           - name: display
#             label: 'Display Type'
#             widget: string
#             default: 'standalone'
#             required: true
#           - name: theme_color
#             label: 'Theme Color'
#             widget: string
#             default: '#000000'
#             required: true
#           - name: background_color
#             label: 'Theme Color'
#             widget: string
#             default: '#FFFFFF'
#             required: true
#           - name: icons
#             widget: list
#             label: 'Icons'
#             allow_add: true
#             fields:
#               - widget: string
#                 name: src
#                 label: Source
#               - widget: string
#                 name: sizes
#                 label: 'Sizes'
#               - widget: string
#                 name: type
#                 label: 'Mime Type'
collections:
  - name: "meetups"
    label: "Meetups"
    description: "Meetup dates, location, and presenter information."
    folder: "src/pages/meetups"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "meetup" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: Presenters,
          name: presenters,
          required: true,
          widget: list,
          fields:
            [
              { label: Name, name: name, required: true, widget: string },
              {
                label: Presentation Title,
                name: presentationTitle,
                required: false,
                widget: string,
              },
              {
                label: Image,
                name: image,
                required: false,
                hint: "If an image isn't specified, a default headshot placeholder image will be used",
                widget: image,
              },
              { label: Text, name: text, required: true, widget: text },
              {
                label: Links,
                name: links,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Text, name: linkText, widget: string },
                    { label: URL, name: linkURL, widget: string },
                  ],
              },
            ],
        }
      - {
          label: "Location",
          name: "location",
          required: true,
          widget: "object",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Google Maps Link", name: "mapsLink", widget: "string" },
              { label: "Latitude", name: "mapsLatitude", widget: "number", valueType: "float" },
              { label: "Longitude", name: "mapsLongitude", widget: "number", valueType: "float" },
            ],
        }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Image Gallery",
              name: "gallery",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Developer Groups", name: "developerGroups", widget: "markdown" }
          - {
              label: "Meetup Organizers",
              name: "organizers",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Images",
                    name: "gallery",
                    widget: "list",
                    fields:
                      [
                        { label: "Name", name: "name", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" },
                      ],
                  },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/pastMeetups/index.md"
        label: "Past Meetups"
        name: "pastMeetups"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "past-meetups-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - {
              label: "Header Image",
              name: "headerImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Upcoming Meetup Heading", name: "upcomingMeetupHeading", widget: "string" }
          - { label: "No Upcoming Meetup Text", name: "noUpcomingMeetupText", hint: "This text will be displayed when there are no upcoming meetups", required: true, widget: "string" }
          - { label: "Maps Note", name: "mapsNote", required: true, widget: "string" }
          - {
              label: "Call to Actions",
              name: "callToActions",
              required: true,
              widget: "object",
              fields:
                [
                  {
                    label: "First CTA",
                    name: "firstCTA",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {
                          label: "Link Type",
                          name: "linkType",
                          widget: "select",
                          options: ["internal", "external"],
                        },
                        {
                          label: "Link URL",
                          name: "linkURL",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                        }
                      ]
                  },
                  {
                    label: "Second CTA",
                    name: "secondCTA",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {
                          label: "Link Type",
                          name: "linkType",
                          widget: "select",
                          options: ["internal", "external"],
                        },
                        {
                          label: "Link URL",
                          name: "linkURL",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                        }
                      ]
                  }
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/pages/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }
                